// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/email-report/WeeklyEmailReport.tsx": () => import("../components/mockups/email-report/WeeklyEmailReport.tsx"),
  "./components/mockups/salesledger-logo/Scheme1.tsx": () => import("../components/mockups/salesledger-logo/Scheme1.tsx"),
  "./components/mockups/salesledger-logo/Scheme2.tsx": () => import("../components/mockups/salesledger-logo/Scheme2.tsx"),
  "./components/mockups/salesledger-logo/Scheme3.tsx": () => import("../components/mockups/salesledger-logo/Scheme3.tsx")
};
