// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/email-report/WeeklyEmailReport.tsx": () => import("../components/mockups/email-report/WeeklyEmailReport.tsx")
};
